<section class="categories-content grid">
  <article class="categories-list grid-item">
    <div class="left">
      <div class="categories-title">Fashion & Clothing</div>
      <ul>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li><a href="#">See More >></a></li>
      </ul>
    </div>
    <div class="right">
      <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/image-categories.PNG')?>" alt="">
    </div>
  </article>
  <article class="categories-list grid-item">
    <div class="left">
      <div class="categories-title">Fashion & Clothing</div>
      <ul>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
      </ul>
      <a href="#">See More >></a>
    </div>
    <div class="right">
      <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/image-categories.PNG')?>" alt="">
    </div>
  </article>
  <article class="categories-list grid-item">
    <div class="left">
      <div class="categories-title">Fashion & Clothing</div>
      <ul>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li><a href="#">See More >></a></li>
      </ul>
    </div>
    <div class="right">
      <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/image-categories.PNG')?>" alt="">
    </div>
  </article>
  <article class="categories-list grid-item">
    <div class="left">
      <div class="categories-title">Fashion & Clothing</div>
      <ul>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li>Men Fashion</li>
        <li><a href="#">See More >></a></li>
      </ul>

    </div>
    <div class="right">
      <img src="<?php echo $this->getViewFileUrl('Magento_Theme::images/image-categories.PNG')?>" alt="">
    </div>
  </article>
</section>
