<div class="sub-link-content">

  <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
      <div class="collapsible mobile-collapsible">
          <h3 class="block-title heading">My account</h3>
          <span class="toggle-tab mobile" style="display: none;"><span class="hidden">hidden</span></span>
          <div class="block-content block-content-statick toggle-content">
              <ul class="bullet">
                  <li><a href="#">Sign In</a></li>
                  <li><a href="#">View Cart</a></li>
                  <li><a href="#">Order Status</a></li>
                  <li><a href="#">Help</a></li>
                  <li><a href="#">Returns</a></li>
                  <li><a href="#">International</a></li>
              </ul>
          </div>
      </div>
  </div>
  <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
      <div class="collapsible mobile-collapsible">
          <h3 class="block-title heading">My account</h3>
          <span class="toggle-tab mobile" style="display: none;"><span class="hidden">hidden</span></span>
          <div class="block-content block-content-statick toggle-content">
              <ul class="bullet">
                  <li><a href="#">Sign In</a></li>
                  <li><a href="#">View Cart</a></li>
                  <li><a href="#">Order Status</a></li>
                  <li><a href="#">Help</a></li>
                  <li><a href="#">Returns</a></li>
                  <li><a href="#">International</a></li>
              </ul>
          </div>
      </div>
  </div>
  <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
      <div class="collapsible mobile-collapsible">
          <h3 class="block-title heading">Information</h3>
          <span class="toggle-tab mobile" style="display: none;"><span class="hidden">hidden</span></span>
          <div class="block-content block-content-statick toggle-content">
              <ul class="bullet">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Privacy Policy</a></li>
                  <li><a href="#">Customer Service</a></li>
                  <li><a href="#">Orders and Returns</a></li>
                  <li><a href="#">Contact</a></li>
                  <li><a href="#">Advanced Search</a></li>
              </ul>
          </div>
      </div>
  </div>
  <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
      <div class="collapsible mobile-collapsible">
          <h3 class="block-title heading">Customer Care</h3>
          <span class="toggle-tab mobile" style="display: none;"><span class="hidden">hidden</span></span>
          <div class="block-content block-content-statick toggle-content">
              <ul class="bullet">
                  <li><a href="#">Terms of Use</a></li>
                  <li><a href="#">Payment Methods</a></li>
                  <li><a href="#">Shipping Guide</a></li>
                  <li><a href="#">Locations We Ship To</a></li>
                  <li><a href="#">Estimated Delivery Time</a></li>
                  <li><a href="#">Sitemap</a></li>
              </ul>
          </div>
      </div>
  </div>

</div>

<div class="row">
  <div class="icon-download">
    <span class="block-title heading"><strong>DOWN LOAD APP</strong></span>
    <ul>
      <li><img src="<?php echo $this->getViewFileUrl('images/google-play.PNG')?>" alt=""></li>
      <li><img src="<?php echo $this->getViewFileUrl('images/app-store.PNG')?>" alt=""></li>
      <li><img src="<?php echo $this->getViewFileUrl('images/window-phone.PNG')?>" alt=""></li>
    </ul>
  </div>
  <div class="shop-by-region ">
    <span class="block-title heading"><strong>SHOP BY REGION:</strong></span>
    <ul class="of-shop-by">
      <li>United States</li>
      <li>Canada</li>
      <li>Japan</li>
      <li>China</li>
    </ul>
  </div>
</div>
