<div class="search-area">
    <a href="javascript:void(0);" class="search-icon"><i class="icon-search"></i></a>
    <form id="search_mini_form" action="//www.newsmartwave.net/magento/porto/index.php/demo5_en/catalogsearch/result/" method="get">
        <div class="form-search ">
            <label for="search">Search:</label>
            <input id="search" type="text" name="q" class="input-text" autocomplete="off" placeholder="Search...">
            <select id="cat" name="cat">
                <option value="">All Categories</option>
                <option value="276">Fashion</option>
                <option value="280">- Woman</option>
                <option value="281">- Jewellery</option>
                <option value="282">- Men</option>
                <option value="283">- Kids Fashion</option>
                <option value="277">Electronics</option>
                <option value="278">Home &amp; Garden</option>
                <option value="279">Motors</option>
                <option value="298">- Cars and Trucks</option>
                <option value="299">- Motorcycles &amp; Powersports</option>
                <option value="300">- Parts &amp; Accessories</option>
                <option value="301">- Auto Tools &amp; Supplies</option>
            </select>
            <button type="submit" title="Search" class="button"><i class="fa fa-search icons"></i></button>
            <div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
            <div class="clearer"></div>
        </div>
    </form>
</div>
