<div class="promo-block">
   <div class="block-promo-1-2column">
      <div class="promo-left promo-col">
         <div class="promo woman-fashion">
            <img src="http://magespid.nextmp.net/Fashion/pub/media/wysiwyg/home/woman-fashion.jpg" alt="">
            <div class="caption">
               <h3>Exiting Collection <br> For <strong>Women</strong></h3>
               <div class="button-action"><a class="button orange-button" href="http://magespid.nextmp.net/Fashion/women.html">SHOP NOW</a> <a class="button yellow-button" href="http://magespid.nextmp.net/Fashion/about-us">READ MORE</a></div>
            </div>
         </div>
      </div>
      <div class="promo-right">
         <div class="promo-newcollection  promo-col">
            <div class="promo watch-purse">
               <img src="http://magespid.nextmp.net/Fashion/pub/media/wysiwyg/home/watch-purse.jpg" alt="">
               <div class="caption">
                  <h2>NEW COLLECTION</h2>
                  <h3>#NEWARRIVALS <br> READY TO ROCK ?</h3>
                  <div class="button-action"><a class="button orange-button" href="http://magespid.nextmp.net/Fashion/women/tops-women.html">SHOP NOW</a></div>
               </div>
            </div>
         </div>
         <div class="promo-col promo-sale">
            <div class="promo"><a href="http://magespid.nextmp.net/Fashion/sale.html"><img src="http://magespid.nextmp.net/Fashion/pub/media/wysiwyg/home/sale.jpg" alt=""></a></div>
         </div>
      </div>
   </div>
   <div class="block-promo-2column">
      <div class="promo-left  promo-col">
         <div class="promo man-fashion">
            <img src="http://magespid.nextmp.net/Fashion/pub/media/wysiwyg/home/man-fashion.jpg" alt="">
            <div class="caption">
               <h2>Man</h2>
               <h3>BREAK THE RULES AND <br> SHOW YOURSELF</h3>
               <div class="button-action"><a class="button blue-button" href="http://magespid.nextmp.net/Fashion/men.html">SHOP NOW</a></div>
            </div>
         </div>
      </div>
      <div class="promo-right  promo-col">
         <div class="promo promo-discover">
            <img src="http://magespid.nextmp.net/Fashion/pub/media/wysiwyg/home/discover.jpg" alt="">
            <div class="caption">
               <h3>DISCOVER THE <br> A MAG CLUB. MORE THAN <br> A FASHION WORLD!</h3>
               <div class="button-action"><a class="button yellow-button" href="http://magespid.nextmp.net/Fashion/women.html">SHOP NOW</a></div>
            </div>
         </div>
      </div>
   </div>
   <div class="block-promo-3column">
      <div class="promo-col">
         <div class="promo promo-kids">
            <img src="http://magespid.nextmp.net/Fashion/pub/media/wysiwyg/home/kids.jpg" alt="">
            <div class="caption">
               <h2>KIDS</h2>
               <h3>CHILDREN TERRITORY <br> BE YOUR OWN HERO!</h3>
               <div class="button-action"><a class="button black-button" href="http://magespid.nextmp.net/Fashion/gear.html">SHOP NOW</a></div>
            </div>
         </div>
      </div>
      <div class="promo-col">
         <div class="promo promo-accessories">
            <img src="http://magespid.nextmp.net/Fashion/pub/media/wysiwyg/home/accessories.jpg" alt="">
            <div class="caption">
               <h2>Accessories</h2>
               <h3>BREAK THE RULES AND <br> SHOW YOURSELF</h3>
               <div class="button-action"><a class="button orange-button" href="http://magespid.nextmp.net/Fashion/gear/bags.html">SHOP NOW</a></div>
            </div>
         </div>
      </div>
      <div class="promo-col">
         <div class="promo fashion-designer">
            <img src="http://magespid.nextmp.net/Fashion/pub/media/wysiwyg/home/fashion-designer.jpg" alt="">
            <div class="caption">
               <h3>FASHION <br> DESIGNER</h3>
               <span>Of the year</span>
            </div>
         </div>
      </div>
   </div>
</div>
