<div class="header-bottom header-sticker">
   <div class="container">
      <div class="row">
         <div class="col-lg-12">
            <div class="border-bottom">
               <div class="custom-menu">
                  <div class="vmagicmenu clearfix">
                     <div class="block-title block-title-vmagicmenu">
                        <strong>
                        <span class="fa icon icon-category-icon"></span>
                        <span class="vmagicmenu-subtitle">Shop by Categories</span>
                        </strong>
                     </div>
                     <div class="block-vmagicmenu-content">
                        <ul class="vmagicmenu-narrow clearfix">
                           <li class="level0 cat first hasChild">
                              <a class="level-top" href="#"><span>Laptop &amp; computers</span><span class="boder-menu"></span></a>
                              <div class="level-top-mega" style="top: 15px;">
                                 <div class="content-mega">
                                    <div class="content-mega-horizontal" style="width: 880px;">
                                       <ul class="level0 mage-column cat-mega" style="width: 900px;">
                                          <li class="children level1">
                                             <a class="a-image" href="#"><img class="img-responsive" alt="Computers &amp; Accessories" src="http://alothemes.com/demo/electro/media/catalog/category/cache/180x118//MobileDevices_01.jpg"></a><a href="#/laptop-computers/computers-accessories.html"><span>Computers &amp; Accessories</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>Laptops<span class="cat_label Sale">Sale</span></span></a></li>
                                                <li class="level2"><a href="#"><span>Computers &amp; Accessories</span></a></li>
                                                <li class="level2"><a href="#"><span>Desktops &amp; Monitors</span></a></li>
                                                <li class="level2"><a href="#"><span>Pen Drives</span></a></li>
                                                <li class="level2"><a href="#"><span>Hard Drives</span></a></li>
                                                <li class="level2"><a href="#"><span>Memory Cards</span></a></li>
                                                <li class="level2"><a href="#"><span>Printers &amp; Ink</span></a></li>
                                                <li class="level2"><a href="#"><span>Networking</span></a></li>
                                                <li class="level2"><a href="#"><span>Internet Devices</span></a></li>
                                                <li class="level2"><a href="#"><span>Software</span></a></li>
                                             </ul>
                                          </li>
                                          <li class="children level1">
                                             <a class="a-image" href="#"><img class="img-responsive" alt="Cameras" src="http://alothemes.com/demo/electro/media/catalog/category/cache/180x118//cameras_01.jpg"></a><a href="#/laptop-computers/cameras.html"><span>Cameras</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>Cameras &amp; Photography</span></a></li>
                                                <li class="level2"><a href="#"><span>Digital SLRs<span class="cat_label New">New</span></span></a></li>
                                                <li class="level2"><a href="#"><span>Point &amp; Shoot Cameras</span></a></li>
                                                <li class="level2"><a href="#"><span>Lenses</span></a></li>
                                                <li class="level2"><a href="#"><span>Camera Accessories</span></a></li>
                                                <li class="level2"><a href="#"><span>Security &amp; Surveillance</span></a></li>
                                                <li class="level2"><a href="#"><span>Binoculars &amp; Telescopes</span></a></li>
                                                <li class="level2"><a href="#"><span>Camcorders</span></a></li>
                                             </ul>
                                          </li>
                                          <li class="children level1">
                                             <a class="a-image" href="#"><img class="img-responsive" alt="Photography" src="http://alothemes.com/demo/electro/media/catalog/category/cache/180x118//6_01.jpg"></a><a href="#/laptop-computers/photography.html"><span>Photography</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>Smartphones</span></a></li>
                                                <li class="level2"><a href="#"><span>Video games</span></a></li>
                                                <li class="level2"><a href="#"><span>Tablets</span></a></li>
                                                <li class="level2"><a href="#"><span>Consoles</span></a></li>
                                             </ul>
                                          </li>
                                          <li class="children level1">
                                             <a class="a-image" href="#"><img class="img-responsive" alt="Office &amp; Stationery" src="http://alothemes.com/demo/electro/media/catalog/category/cache/180x118//5_01.jpg"></a><a href="#/laptop-computers/office-stationery.html"><span>Office &amp; Stationery</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>All Office &amp; Stationery</span></a></li>
                                                <li class="level2"><a href="#"><span>Pens &amp; Writing</span></a></li>
                                                <li class="level2"><a href="#"><span>Trending styles</span></a></li>
                                             </ul>
                                          </li>
                                          <li></li>
                                       </ul>
                                    </div>
                                 </div>
                              </div>
                           </li>
                           <li class="level0 cat  hasChild" data-options="{&quot;menu_id&quot;:&quot;10&quot;,&quot;cat_columns&quot;:&quot;2&quot;,&quot;cat_proportions&quot;:&quot;2&quot;,&quot;right_proportions&quot;:null,&quot;left_proportions&quot;:null}">
                              <a class="level-top" href="#"><span>Smartphones &amp; tablets</span><span class="boder-menu"></span></a>
                              <div class="level-top-mega" style="top: 56.8px;">
                                 <div class="content-mega">
                                    <div class="content-mega-horizontal" style="width: 440px;">
                                       <ul class="level0 mage-column cat-mega" style="width: 460px;">
                                          <li class="children level1">
                                             <a href="#"><span>Video games</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>All Consoles</span></a></li>
                                                <li class="level2"><a href="#"><span>Games &amp; Accessories</span></a></li>
                                                <li class="level2"><a href="#"><span>PC Games</span></a></li>
                                                <li class="level2"><a href="#"><span>New Releases</span></a></li>
                                                <li class="level2"><a href="#"><span>Accessories</span></a></li>
                                             </ul>
                                          </li>
                                          <li class="children level1">
                                             <a href="#"><span>TV &amp; audio</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>Computers</span></a></li>
                                                <li class="level2"><a href="#"><span>Movies &amp; TV Shows</span></a></li>
                                                <li class="level2"><a href="#"><span>Blu-ray</span></a></li>
                                                <li class="level2"><a href="#"><span>All English</span></a></li>
                                                <li class="level2"><a href="#"><span>All Hindi</span></a></li>
                                             </ul>
                                          </li>
                                          <li class="children level1" style="clear: both;">
                                             <a href="#"><span>Music</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>All Music</span></a></li>
                                                <li class="level2"><a href="#"><span>International Music</span></a></li>
                                                <li class="level2"><a href="#"><span>Film Songs</span></a></li>
                                             </ul>
                                          </li>
                                          <li class="children level1">
                                             <a href="#"><span>Smartphones</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>Video games</span></a></li>
                                                <li class="level2"><a href="#"><span>Photography</span></a></li>
                                             </ul>
                                          </li>
                                          <li>
                                             <div class="mage-column mega-block-bottom">
                                                <div class="img-menu"><img class="img-responsive" src="http://alothemes.com/demo/electro/media/wysiwyg/alothemes/static/megamenu-bottom.png" alt=""></div>
                                             </div>
                                          </li>
                                       </ul>
                                    </div>
                                 </div>
                              </div>
                           </li>
                           <li class="level0 cat  hasChild dropdown">
                              <a class="level-top" href="#"><span>Cameras</span><span class="boder-menu"></span></a>
                              <ul class="level0">
                                 <li class="level1 hasChild">
                                    <a href="#"><span>Cameras</span></a>
                                    <ul class="level1">
                                       <li class="level2"><a href="#"><span>Smartphones</span></a></li>
                                       <li class="level2"><a href="#"><span>Video games</span></a></li>
                                       <li class="level2"><a href="#"><span>TV &amp; audio</span></a></li>
                                       <li class="level2"><a href="#"><span>Computers</span></a></li>
                                    </ul>
                                 </li>
                                 <li class="level1"><a href="#"><span>Photography</span></a></li>
                                 <li class="level1 hasChild">
                                    <a href="#"><span>Gadgets</span></a>
                                    <ul class="level1">
                                       <li class="level2"><a href="#"><span>Consoles</span></a></li>
                                       <li class="level2"><a href="#"><span>Audio</span></a></li>
                                       <li class="level2"><a href="#"><span>Smartphones</span></a></li>
                                       <li class="level2"><a href="#"><span>Video games</span></a></li>
                                       <li class="level2"><a href="#"><span>TV &amp; audio</span></a></li>
                                    </ul>
                                 </li>
                              </ul>
                           </li>
                           <li class="level0 cat  hasChild" data-options="{&quot;menu_id&quot;:&quot;12&quot;,&quot;cat_columns&quot;:null,&quot;cat_proportions&quot;:null,&quot;right_proportions&quot;:null,&quot;left_proportions&quot;:null}">
                              <a class="level-top" href="#"><span>Video games &amp; consoles</span><span class="boder-menu"></span></a>
                              <div class="level-top-mega" style="top: 140.4px;">
                                 <div class="content-mega">
                                    <div class="content-mega-horizontal" style="width: 660px;">
                                       <ul class="level0 mage-column cat-mega" style="width: 680px;">
                                          <li class="children level1">
                                             <a href="#"><span>Car &amp; Motorbike</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>Photography</span></a></li>
                                                <li class="level2"><a href="#"><span>All Cars &amp; Bikes</span></a></li>
                                                <li class="level2"><a href="#"><span>Car &amp; Bike Care</span></a></li>
                                                <li class="level2"><a href="#"><span>Lubricants</span></a></li>
                                             </ul>
                                          </li>
                                          <li class="children level1">
                                             <a href="#"><span>Consoles</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>Photography</span></a></li>
                                                <li class="level2"><a href="#"><span>Air Fresheners</span></a></li>
                                                <li class="level2"><a href="#"><span>Car Parts</span></a></li>
                                                <li class="level2"><a href="#"><span>Tyre Accessories</span></a></li>
                                             </ul>
                                          </li>
                                          <li class="children level1">
                                             <a href="#"><span>Shop for Bike</span></a>
                                             <ul class="level1">
                                                <li class="level2"><a href="#"><span>Helmets &amp; Gloves</span></a></li>
                                                <li class="level2"><a href="#"><span>Bike Parts</span></a></li>
                                             </ul>
                                          </li>
                                          <li>
                                             <div class="mage-column mega-block-bottom">
                                                <div class="cms-static-banner-menu-bottom banner-menu-bottom">
                                                   <div class="banner-menu-box"><a href="#"><img class="img-responsive" alt="" src="http://alothemes.com/demo/electro/media/wysiwyg/alothemes/static/megamenu-bottom.jpg"></a></div>
                                                </div>
                                             </div>
                                          </li>
                                       </ul>
                                    </div>
                                 </div>
                              </div>
                           </li>
                           <li class="level0 cat "><a class="level-top" href="#"><span>TV &amp; audio</span><span class="boder-menu"></span></a></li>
                           <li class="level0 cat "><a class="level-top" href="#"><span>Gadgets</span><span class="boder-menu"></span></a></li>
                           <li class="level0 cat "><a class="level-top" href="#"><span>Cart electronics &amp; GPS</span><span class="boder-menu"></span></a></li>
                           <li class="level0 cat "><a class="level-top" href="#"><span>Accessories</span><span class="boder-menu"></span></a></li>
                           <li class="level0 cat "><a class="level-top" href="#"><span>Software</span><span class="boder-menu"></span></a></li>
                           <li class="level0 cat "><a class="level-top" href="#"><span>Printers &amp; Ink</span><span class="boder-menu"></span></a></li>
                           <li class="level0 cat " style="display: none;"><a class="level-top" href="#"><span>Car Electronic &amp; GPS</span><span class="boder-menu"></span></a></li>
                           <li class="level0 cat last" style="display: none;"><a class="level-top" href="#"><span>Office Supplies</span><span class="boder-menu"></span></a></li>
                        </ul>
                        <div class="all-cat"><span style="display: block;">All Categories</span><span style="display: none;">Close</span></div>
                     </div>
                  </div>
                  <div class="magicmenu clearfix">
                     <ul class="nav-desktop sticker" data-fullwidth="0">
                        <li class="level0 home active">
                           <a class="level-top" href="#"><span class="icon-home fa fa-home"></span><span class="icon-text">Home</span></a>
                           <div class="level-top-mega" style="left: 284.1px;">
                              <div><a href="#"><span class="demo-home">Demo 1</span></a></div>
                              <div><a href="#"><span class="demo-home">Demo 2</span></a></div>
                              <div><a href="#"><span class="demo-home">Demo 3</span></a></div>
                           </div>
                        </li>
                        <li class="level0 cat first hasChild">
                           <a class="level-top" href="#"><span>Daily Deals</span><span class="boder-menu"></span></a>
                           <div class="level-top-mega" style="left: 258px;">
                              <div class="content-mega">
                                 <div class="content-mega-horizontal" style="width: 880px;">
                                    <ul class="level0 mage-column cat-mega">
                                       <li class="children level1">
                                          <a class="a-image" href="#"><img class="img-responsive" alt="Computers &amp; Accessories" src="http://alothemes.com/demo/electro/media/catalog/category/cache/180x118//MobileDevices_01.jpg"></a><a href="#/laptop-computers/computers-accessories.html"><span>Computers &amp; Accessories</span></a>
                                          <ul class="level1">
                                             <li class="level2"><a href="#"><span>Laptops<span class="cat_label Sale">Sale</span></span></a></li>
                                             <li class="level2"><a href="#"><span>Computers &amp; Accessories</span></a></li>
                                             <li class="level2"><a href="#"><span>Desktops &amp; Monitors</span></a></li>
                                             <li class="level2"><a href="#"><span>Pen Drives</span></a></li>
                                             <li class="level2"><a href="#"><span>Hard Drives</span></a></li>
                                             <li class="level2"><a href="#"><span>Memory Cards</span></a></li>
                                             <li class="level2"><a href="#"><span>Printers &amp; Ink</span></a></li>
                                             <li class="level2"><a href="#"><span>Networking</span></a></li>
                                             <li class="level2"><a href="#"><span>Internet Devices</span></a></li>
                                             <li class="level2"><a href="#"><span>Software</span></a></li>
                                          </ul>
                                       </li>
                                       <li class="children level1">
                                          <a class="a-image" href="#/laptop-computers/cameras.html"><img class="img-responsive" alt="Cameras" src="http://alothemes.com/demo/electro/media/catalog/category/cache/180x118//cameras_01.jpg"></a><a href="#/laptop-computers/cameras.html"><span>Cameras</span></a>
                                          <ul class="level1">
                                             <li class="level2"><a href="#/laptop-computers/cameras/cameras-photography.html"><span>Cameras &amp; Photography</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/cameras/digital-slrs.html"><span>Digital SLRs<span class="cat_label New">New</span></span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/cameras/point-shoot-cameras.html"><span>Point &amp; Shoot Cameras</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/cameras/lenses.html"><span>Lenses</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/cameras/camera-accessories.html"><span>Camera Accessories</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/cameras/security-surveillance.html"><span>Security &amp; Surveillance</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/cameras/binoculars-telescopes.html"><span>Binoculars &amp; Telescopes</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/cameras/camcorders.html"><span>Camcorders</span></a></li>
                                          </ul>
                                       </li>
                                       <li class="children level1">
                                          <a class="a-image" href="#/laptop-computers/photography.html"><img class="img-responsive" alt="Photography" src="http://alothemes.com/demo/electro/media/catalog/category/cache/180x118//6_01.jpg"></a><a href="#/laptop-computers/photography.html"><span>Photography</span></a>
                                          <ul class="level1">
                                             <li class="level2"><a href="#/laptop-computers/photography/smartphones.html"><span>Smartphones</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/photography/video-games.html"><span>Video games</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/photography/tablets.html"><span>Tablets</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/photography/consoles.html"><span>Consoles</span></a></li>
                                          </ul>
                                       </li>
                                       <li class="children level1">
                                          <a class="a-image" href="#/laptop-computers/office-stationery.html"><img class="img-responsive" alt="Office &amp; Stationery" src="http://alothemes.com/demo/electro/media/catalog/category/cache/180x118//5_01.jpg"></a><a href="#/laptop-computers/office-stationery.html"><span>Office &amp; Stationery</span></a>
                                          <ul class="level1">
                                             <li class="level2"><a href="#/laptop-computers/office-stationery/all-office-stationery.html"><span>All Office &amp; Stationery</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/office-stationery/pens-writing.html"><span>Pens &amp; Writing</span></a></li>
                                             <li class="level2"><a href="#/laptop-computers/office-stationery/trending-styles.html"><span>Trending styles</span></a></li>
                                          </ul>
                                       </li>
                                       <li></li>
                                    </ul>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li class="level0 cat  hasChild" data-options="{&quot;menu_id&quot;:&quot;11&quot;,&quot;cat_columns&quot;:&quot;3&quot;,&quot;cat_proportions&quot;:&quot;3&quot;,&quot;right_proportions&quot;:&quot;1&quot;,&quot;left_proportions&quot;:null}" style="clear: both;">
                           <a class="level-top" href="#/motorbike.html"><span>Trending Products</span><span class="boder-menu"></span></a>
                           <div class="level-top-mega" style="left: 258px;">
                              <div class="content-mega">
                                 <div class="content-mega-horizontal" style="width: 880px;">
                                    <ul class="level0 mage-column cat-mega" style="width: 75%;">
                                       <li class="children level1">
                                          <a href="#/motorbike/industrial-supplies.html"><span>Industrial Supplies</span></a>
                                          <ul class="level1">
                                             <li class="level2"><a href="#/motorbike/industrial-supplies/all-industrial-supplies.html"><span>All Industrial Supplies</span></a></li>
                                             <li class="level2"><a href="#/motorbike/industrial-supplies/lab-scientific.html"><span>Lab &amp; Scientific</span></a></li>
                                             <li class="level2"><a href="#/motorbike/industrial-supplies/janitorial.html"><span>Janitorial</span></a></li>
                                             <li class="level2"><a href="#/motorbike/industrial-supplies/sanitation-supplies.html"><span>Sanitation Supplies</span></a></li>
                                          </ul>
                                       </li>
                                       <li class="children level1">
                                          <a href="#/motorbike/car-motorbike.html"><span>Car &amp; Motorbike</span></a>
                                          <ul class="level1">
                                             <li class="level2"><a href="#/motorbike/car-motorbike/all-cars-bikes.html"><span>All Cars &amp; Bikes</span></a></li>
                                             <li class="level2"><a href="#/motorbike/car-motorbike/measure-inspect.html"><span>Measure &amp; Inspect</span></a></li>
                                             <li class="level2"><a href="#/motorbike/car-motorbike/car-bike-care.html"><span>Car &amp; Bike Care</span></a></li>
                                             <li class="level2"><a href="#/motorbike/car-motorbike/lubricants.html"><span>Lubricants</span></a></li>
                                          </ul>
                                       </li>
                                       <li class="children level1">
                                          <a href="#/motorbike/shop-for-bike.html"><span>Shop for Bike</span></a>
                                          <ul class="level1">
                                             <li class="level2"><a href="#/motorbike/shop-for-bike/helmets-gloves.html"><span>Helmets &amp; Gloves</span></a></li>
                                             <li class="level2"><a href="#/motorbike/shop-for-bike/bike-parts.html"><span>Bike Parts</span></a></li>
                                             <li class="level2"><a href="#/motorbike/shop-for-bike/scarves.html"><span>Scarves</span></a></li>
                                             <li class="level2"><a href="#/motorbike/shop-for-bike/skirts.html"><span>Skirts</span></a></li>
                                          </ul>
                                       </li>
                                       <li class="children level1">
                                          <a href="#/motorbike/shop-for-car.html"><span>Shop for Car</span></a>
                                          <ul class="level1">
                                             <li class="level2"><a href="#/motorbike/shop-for-car/air-fresheners.html"><span>Air Fresheners</span></a></li>
                                             <li class="level2"><a href="#/motorbike/shop-for-car/car-parts.html"><span>Car Parts</span></a></li>
                                             <li class="level2"><a href="#/motorbike/shop-for-car/tyre-accessories.html"><span>Tyre Accessories</span></a></li>
                                          </ul>
                                       </li>
                                       <li class="children level1">
                                          <a href="#/motorbike/football.html"><span>Football</span></a>
                                          <ul class="level1">
                                             <li class="level2"><a href="#/motorbike/football/coats-jackets.html"><span>Coats &amp; Jackets</span></a></li>
                                             <li class="level2"><a href="#/motorbike/football/blouses-shirts.html"><span>Blouses &amp; Shirts</span></a></li>
                                             <li class="level2"><a href="#/motorbike/football/tops-tees.html"><span>Tops &amp; Tees</span></a></li>
                                          </ul>
                                       </li>
                                       <li></li>
                                    </ul>
                                    <div class="mage-column mega-block-right" style="width: 25%;">
                                       <div class="cms-static-banner-menu-right banner-menu-right">
                                          <div class="banner-menu-box"><a href="#"><img class="img-reponsive" alt="" src="http://alothemes.com/demo/electro/media/wysiwyg/alothemes/static/megamenu-right.jpg"></a></div>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </li>
                        <li class="level0 ext  first"><a class="level-top" href="#/yoko/"><span>Featured brands</span></a></li>
                        <li class="level0 ext  "><a class="level-top" href="#/blog/"><span>Best Sallers</span></a></li>
                        <li class="level0 ext  last"><a class="level-top" href="#/about-magento-demo-store/"><span>Events Sale</span></a></li>
                     </ul>
                  </div>
                  <div class="nav-mobile" style="display: none;">
                     <h3 class="mobi-title">Categories</h3>
                     <ul>
                        <li class="level0">
                           <a class="level-top" href="#/laptop-computers.html"><span>Laptop &amp; computers</span><span class="boder-menu"></span></a>
                           <ul>
                              <li>
                                 <a href="#/laptop-computers/computers-accessories.html"><span>Computers &amp; Accessories</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/laptops.html"><span>Laptops<span class="cat_label Sale">Sale</span></span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/computers-accessories.html"><span>Computers &amp; Accessories</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/desktops-monitors.html"><span>Desktops &amp; Monitors</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/pen-drives.html"><span>Pen Drives</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/hard-drives.html"><span>Hard Drives</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/memory-cards.html"><span>Memory Cards</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/printers-ink.html"><span>Printers &amp; Ink</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/networking.html"><span>Networking</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/internet-devices.html"><span>Internet Devices</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/computers-accessories/software.html"><span>Software</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/laptop-computers/cameras.html"><span>Cameras</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/laptop-computers/cameras/cameras-photography.html"><span>Cameras &amp; Photography</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/cameras/digital-slrs.html"><span>Digital SLRs<span class="cat_label New">New</span></span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/cameras/point-shoot-cameras.html"><span>Point &amp; Shoot Cameras</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/cameras/lenses.html"><span>Lenses</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/cameras/camera-accessories.html"><span>Camera Accessories</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/cameras/security-surveillance.html"><span>Security &amp; Surveillance</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/cameras/binoculars-telescopes.html"><span>Binoculars &amp; Telescopes</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/cameras/camcorders.html"><span>Camcorders</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/laptop-computers/photography.html"><span>Photography</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/laptop-computers/photography/smartphones.html"><span>Smartphones</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/photography/video-games.html"><span>Video games</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/photography/tablets.html"><span>Tablets</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/photography/consoles.html"><span>Consoles</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/laptop-computers/office-stationery.html"><span>Office &amp; Stationery</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/laptop-computers/office-stationery/all-office-stationery.html"><span>All Office &amp; Stationery</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/office-stationery/pens-writing.html"><span>Pens &amp; Writing</span></a></li>
                                    <li class="level2"><a href="#/laptop-computers/office-stationery/trending-styles.html"><span>Trending styles</span></a></li>
                                 </ul>
                              </li>
                           </ul>
                        </li>
                        <li class="level0">
                           <a class="level-top" href="#/smartphones-tablets.html"><span>Smartphones &amp; tablets</span><span class="boder-menu"></span></a>
                           <ul>
                              <li>
                                 <a href="#/smartphones-tablets/video-games.html"><span>Video games</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/smartphones-tablets/video-games/all-consoles.html"><span>All Consoles</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/video-games/games-accessories.html"><span>Games &amp; Accessories</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/video-games/pc-games.html"><span>PC Games</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/video-games/new-releases.html"><span>New Releases</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/video-games/accessories.html"><span>Accessories</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/smartphones-tablets/tv-audio.html"><span>TV &amp; audio</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/smartphones-tablets/tv-audio/computers.html"><span>Computers</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/tv-audio/movies-tv-shows.html"><span>Movies &amp; TV Shows</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/tv-audio/blu-ray.html"><span>Blu-ray</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/tv-audio/all-english.html"><span>All English</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/tv-audio/all-hindi.html"><span>All Hindi</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/smartphones-tablets/music.html"><span>Music</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/smartphones-tablets/music/all-music.html"><span>All Music</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/music/international-music.html"><span>International Music</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/music/film-songs.html"><span>Film Songs</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/smartphones-tablets/smartphones.html"><span>Smartphones</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/smartphones-tablets/smartphones/video-games.html"><span>Video games</span></a></li>
                                    <li class="level2"><a href="#/smartphones-tablets/smartphones/photography.html"><span>Photography</span></a></li>
                                 </ul>
                              </li>
                           </ul>
                        </li>
                        <li class="level0">
                           <a class="level-top" href="#/cameras.html"><span>Cameras</span><span class="boder-menu"></span></a>
                           <ul class="level0">
                              <li class="level1 hasChild">
                                 <a href="#/cameras/cameras.html"><span>Cameras</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/cameras/cameras/smartphones.html"><span>Smartphones</span></a></li>
                                    <li class="level2"><a href="#/cameras/cameras/video-games.html"><span>Video games</span></a></li>
                                    <li class="level2"><a href="#/cameras/cameras/tv-audio.html"><span>TV &amp; audio</span></a></li>
                                    <li class="level2"><a href="#/cameras/cameras/computers.html"><span>Computers</span></a></li>
                                 </ul>
                              </li>
                              <li class="level1"><a href="#/cameras/photography.html"><span>Photography</span></a></li>
                              <li class="level1 hasChild">
                                 <a href="#/cameras/gadgets.html"><span>Gadgets</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/cameras/gadgets/consoles.html"><span>Consoles</span></a></li>
                                    <li class="level2"><a href="#/cameras/gadgets/audio.html"><span>Audio</span></a></li>
                                    <li class="level2"><a href="#/cameras/gadgets/smartphones.html"><span>Smartphones</span></a></li>
                                    <li class="level2"><a href="#/cameras/gadgets/video-games.html"><span>Video games</span></a></li>
                                    <li class="level2"><a href="#/cameras/gadgets/tv-audio.html"><span>TV &amp; audio</span></a></li>
                                 </ul>
                              </li>
                           </ul>
                        </li>
                        <li class="level0">
                           <a class="level-top" href="#/video-games-consoles.html"><span>Video games &amp; consoles</span><span class="boder-menu"></span></a>
                           <ul>
                              <li>
                                 <a href="#/video-games-consoles/car-motorbike.html"><span>Car &amp; Motorbike</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/video-games-consoles/car-motorbike/photography.html"><span>Photography</span></a></li>
                                    <li class="level2"><a href="#/video-games-consoles/car-motorbike/all-cars-bikes.html"><span>All Cars &amp; Bikes</span></a></li>
                                    <li class="level2"><a href="#/video-games-consoles/car-motorbike/car-bike-care.html"><span>Car &amp; Bike Care</span></a></li>
                                    <li class="level2"><a href="#/video-games-consoles/car-motorbike/lubricants.html"><span>Lubricants</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/video-games-consoles/consoles.html"><span>Consoles</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/video-games-consoles/consoles/photography.html"><span>Photography</span></a></li>
                                    <li class="level2"><a href="#/video-games-consoles/consoles/air-fresheners.html"><span>Air Fresheners</span></a></li>
                                    <li class="level2"><a href="#/video-games-consoles/consoles/car-parts.html"><span>Car Parts</span></a></li>
                                    <li class="level2"><a href="#/video-games-consoles/consoles/tyre-accessories.html"><span>Tyre Accessories</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/video-games-consoles/shop-for-bike.html"><span>Shop for Bike</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/video-games-consoles/shop-for-bike/helmets-gloves.html"><span>Helmets &amp; Gloves</span></a></li>
                                    <li class="level2"><a href="#/video-games-consoles/shop-for-bike/bike-parts.html"><span>Bike Parts</span></a></li>
                                 </ul>
                              </li>
                           </ul>
                        </li>
                        <li class="level0">
                           <a class="level-top" href="#/motorbike.html"><span>Motorbike</span><span class="boder-menu"></span></a>
                           <ul>
                              <li>
                                 <a href="#/motorbike/industrial-supplies.html"><span>Industrial Supplies</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/motorbike/industrial-supplies/all-industrial-supplies.html"><span>All Industrial Supplies</span></a></li>
                                    <li class="level2"><a href="#/motorbike/industrial-supplies/lab-scientific.html"><span>Lab &amp; Scientific</span></a></li>
                                    <li class="level2"><a href="#/motorbike/industrial-supplies/janitorial.html"><span>Janitorial</span></a></li>
                                    <li class="level2"><a href="#/motorbike/industrial-supplies/sanitation-supplies.html"><span>Sanitation Supplies</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/motorbike/car-motorbike.html"><span>Car &amp; Motorbike</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/motorbike/car-motorbike/all-cars-bikes.html"><span>All Cars &amp; Bikes</span></a></li>
                                    <li class="level2"><a href="#/motorbike/car-motorbike/measure-inspect.html"><span>Measure &amp; Inspect</span></a></li>
                                    <li class="level2"><a href="#/motorbike/car-motorbike/car-bike-care.html"><span>Car &amp; Bike Care</span></a></li>
                                    <li class="level2"><a href="#/motorbike/car-motorbike/lubricants.html"><span>Lubricants</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/motorbike/shop-for-bike.html"><span>Shop for Bike</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/motorbike/shop-for-bike/helmets-gloves.html"><span>Helmets &amp; Gloves</span></a></li>
                                    <li class="level2"><a href="#/motorbike/shop-for-bike/bike-parts.html"><span>Bike Parts</span></a></li>
                                    <li class="level2"><a href="#/motorbike/shop-for-bike/scarves.html"><span>Scarves</span></a></li>
                                    <li class="level2"><a href="#/motorbike/shop-for-bike/skirts.html"><span>Skirts</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/motorbike/shop-for-car.html"><span>Shop for Car</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/motorbike/shop-for-car/air-fresheners.html"><span>Air Fresheners</span></a></li>
                                    <li class="level2"><a href="#/motorbike/shop-for-car/car-parts.html"><span>Car Parts</span></a></li>
                                    <li class="level2"><a href="#/motorbike/shop-for-car/tyre-accessories.html"><span>Tyre Accessories</span></a></li>
                                 </ul>
                              </li>
                              <li>
                                 <a href="#/motorbike/football.html"><span>Football</span></a>
                                 <ul class="level1">
                                    <li class="level2"><a href="#/motorbike/football/coats-jackets.html"><span>Coats &amp; Jackets</span></a></li>
                                    <li class="level2"><a href="#/motorbike/football/blouses-shirts.html"><span>Blouses &amp; Shirts</span></a></li>
                                    <li class="level2"><a href="#/motorbike/football/tops-tees.html"><span>Tops &amp; Tees</span></a></li>
                                 </ul>
                              </li>
                           </ul>
                        </li>
                        <li class="level0"><a class="level-top" href="#/tv-audio.html"><span>TV &amp; audio</span><span class="boder-menu"></span></a></li>
                        <li class="level0"><a class="level-top" href="#/gadgets.html"><span>Gadgets</span><span class="boder-menu"></span></a></li>
                        <li class="level0"><a class="level-top" href="#/cart-electronics-gps.html"><span>Cart electronics &amp; GPS</span><span class="boder-menu"></span></a></li>
                        <li class="level0"><a class="level-top" href="#/accessories.html"><span>Accessories</span><span class="boder-menu"></span></a></li>
                        <li class="level0"><a class="level-top" href="#/software.html"><span>Software</span><span class="boder-menu"></span></a></li>
                        <li class="level0"><a class="level-top" href="#/printers-ink.html"><span>Printers &amp; Ink</span><span class="boder-menu"></span></a></li>
                        <li class="level0"><a class="level-top" href="#/car-electronic-gps.html"><span>Car Electronic &amp; GPS</span><span class="boder-menu"></span></a></li>
                        <li class="level0"><a class="level-top" href="#/office-supplies.html"><span>Office Supplies</span><span class="boder-menu"></span></a></li>
                        <li class="level0 ext  first"><a class="level-top" href="#/yoko/"><span>Featured brands</span></a></li>
                        <li class="level0 ext  "><a class="level-top" href="#/blog/"><span>Blog</span></a></li>
                        <li class="level0 ext  last"><a class="level-top" href="#/about-magento-demo-store/"><span>About Us</span></a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
