<div class="col-md-4 col-lg-4 col-sm-4 col-xs-4 socials">
    <img src="<?php echo $this->getViewFileUrl('images/icon-call-service.PNG')?>" alt="">
    <div class="infor-call-service">
      <span><?php echo __("Call for Best Services")?></span>
      <span class="cls-phone"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('hotline')->toHtml();?></span>
    </div>

</div>
