<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset" style="">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <span>Quantity:</span>
                <input 
                        style="margin-right: 25px"
                        type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <button type="submit"

                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button"
                    style="margin-right:5px;width: 15%;padding-top: 5px;padding-bottom: 5px; background-color : #0157AE;border-radius: 0px;border: 1px solid #0157AE;";>
                    <span style="color: white"><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>

                <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button"
                    style="width: 15%;padding-top: 5px;padding-bottom: 5px; background-color : white;border-radius: 0px;border: 1px solid #0157AE";>
                    <span style="color: #0157AE "><?php /* @escapeNotVerified */ echo __('Buy It Now') ?></span>
                </button>
            <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
        <?php endif; ?>
      <!--   <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button"
                    style="width: 20%">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div> -->
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>