<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
    $_titleBlock=$block->getTitle();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <div class="col-md-12" style="padding-left: 0px; margin-top: 60px;margin-bottom: 15px;">
            <span style="font-size: 20px;font-weight: 600"><?php echo __($_titleBlock )?></span>
        </div>
        <table class="data table  table-bordered" id="product-attribute-specs-table">
           <!--  <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('More Information') ?></caption> -->
            <tbody>
            <?php foreach ($_additional as $_data): ?>
                <tr>
                    <td class="col data active" scope="row" style="color: black;width: 50%;border-right:0px;"><?php echo $block->escapeHtml(__($_data['label'])) ?></td>
                    <td class="col data" style="border-left:0px;" data-th="<?php echo $block->escapeHtml(__($_data['label'])) ?>"><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>
