<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @description:
 *
 */
?>
<?php
    $_items = $block->getReviewsCollection()->getItems();
    $format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)):?>
<div class="block review-list" id="reviews">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Customer Reviews') ?></strong>
    </div>
    <div class="block-content">
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div>
        <ol class="items review-items">
        <?php foreach ($_items as $_review):?>
            <li class="item review-item" itemscope itemprop="review" style="border-bottom-width :0px; " itemtype="http://schema.org/Review">
                <!-- <div class="review-title" itemprop="name"><?php echo $block->escapeHtml($_review->getTitle()) ?></div> -->
                <?php if (count($_review->getRatingVotes())): ?>
                    <div class="review-ratings">
                    <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                    <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                        
                        <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                            <meta itemprop="worstRating" content = "1"/>
                            <meta itemprop="bestRating" content = "100"/>
                            <span style="height: 20px; width:<?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%">
                                <span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $_vote->getPercent() ?>%</span>
                            </span>
                        </div>
                    </div>
                    <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <div class="review-content" itemprop="description"; style="margin-left: 100px">
                   <!--   $block->escapeHtml($_review->getTitle())  -->
                    <span> <?php echo  $block->get_star_from_pecent ($_vote->getPercent()) ?> out of 5 stars</span> <span style="font-weight: 600" > <?php echo nl2br( $block->escapeHtml($_review->getTitle()) ) ?></span>
                </div>
                <div class="review-details" style="margin-left: 0px">
                    <span class="review-author">
                        <span class="review-details-label"><?php /* @escapeNotVerified */ echo __('By')?></span>
                        <strong class="review-details-value" itemprop="author" style="color: #0157AE">
                            <?php echo $block->escapeHtml($_review->getNickname()) ?>
                        </strong>
                    </span>
                </div>
                <div class="review-details" style="margin-left: 0px">
                    <p>
                        <?php echo nl2br($block->escapeHtml($_review->getDetail())) ?>
                    </p>
                   
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <?php echo $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php endif;?>
