<div class="col-sm-8 block-newletter">
                <div class="block newsletter block-subscribe">
                    <form class="form subscribe clearfix" novalidate="novalidate" action="http://alothemes.com/demo2/bigsale/index.php/newsletter/subscriber/new/" method="post" id="newsletter-validate-detail">
                        <div class="block-content">
                            <div class="col-sm-6 block-title"><p>Join our email for get <strong>PROMO CODE</strong> and <strong>NEWS</strong></p></div>
                            <div class="col-sm-4 field newsletter input-box">
                                <div class="visible">
                                    <div class="control">
                                        <input name="email" type="email" id="newsletter" class="input-text" placeholder="Enter your email address" data-validate="{required:true, 'validate-email':true}">
                                    </div>
                                    <div class="actions">
                                        <button class="action subscribe button" title="Subscribe" type="submit">
                                        <img src="<?php echo $this->getViewFileUrl('images/arrow.PNG')?>" alt="">
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
