<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Catalog\Product\View\Addto\Compare */
?>

<a href="#" 

	data-post='<?php /* @escapeNotVerified */ echo $block->getPostDataParams();?>'
		style="margin-right: 20px"
        data-role="add-to-links"
        <span><?php /* @escapeNotVerified */ echo __('Compare with similar product') ?></span></a>
