<!--banner intro-->

<!--content-->
<div class="content-home">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-8">
                <!--product-->

                <section class="sec-product">
                    <h2 class="title">Women’s Day Discount</h2>
                    <div  class="row">
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img01.png')?>" alt=""></div>
                            <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                            <div class="cost">$250</div>
                            <div class="cost-sale">$300</div>
                            <div class="label-sale">Save 20%</div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img02.png')?>" alt=""></div>
                            <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                            <div class="cost">$250</div>
                            <div class="cost-sale">$300</div>
                            <div class="label-sale">Save 20%</div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img03.png')?>" alt=""></div>
                            <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                            <div class="cost">$250</div>
                            <div class="cost-sale">$300</div>
                            <div class="label-sale">Save 20%</div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img04.png')?>" alt=""></div>
                            <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                            <div class="cost">$250</div>
                            <div class="cost-sale">$300</div>
                            <div class="label-sale">Save 20%</div>
                        </div>
                    </div>
                </section>
                <section class="sec-product newstyle">
                    <h2 class="title">Trending Products</h2>
                    <div  class="row">
                        <div class="col-xs-12 col-sm-6 col-md-4">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img05.png')?>" alt=""></div>
                            <h4 class="title">Hight Heel Shoe</h4>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-4">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img06.png')?>" alt=""></div>
                            <h4 class="title">Diamond Watch</h4>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-4">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img07.png')?>" alt=""></div>
                            <h4 class="title">Luxury Bag</h4>
                        </div>
                    </div>
                </section>
                <section class="sec-banner-center">
                    <article><img src="<?php echo $this->getViewFileUrl('images/small-banner.png')?>" alt=""></article>
                </section>
                <section class="sec-product ">
                    <h2 class="title">Daily Deals</h2>
                    <div  class="row">
                        <div class="col-xs-12 col-sm-6 col-md-4 ">
                            <div class="item">
                                <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img14.png')?>" alt=""></div>
                                <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                                <div class="cost">$250</div>
                            </div>

                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-4 ">
                            <div class="item">
                                <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img15.png')?>" alt=""></div>
                                <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                                <div class="cost">$250</div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-4 ">
                            <div class="item">
                                <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img16.png')?>" alt=""6></div>
                                <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                                <div class="cost">$250</div>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="sec-product">
                    <h2 class="title">Best Selling Products</h2>
                    <div  class="row">
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img17.png')?>" alt=""></div>
                            <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                            <div class="cost">$250</div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img15.png')?>" alt=""></div>
                            <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                            <div class="cost">$250</div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img16.png')?>" alt=""></div>
                            <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                            <div class="cost">$250</div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="view-img"><img src="<?php echo $this->getViewFileUrl('images/img17.png')?>" alt=""></div>
                            <div class="text">Vichy Aqualia Thermal Rich<br />Cream 48 Hour Facial</div>
                            <div class="cost">$250</div>
                        </div>
                    </div>
                </section>
                <section class="sec-banner-center">
                    <article><img src="<?php echo $this->getViewFileUrl('images/banner02.png')?>" alt=""></article>
                </section>
                <!--end-product-->
            </div>
            <div class="col-xs-12  col-md-4">
                <!--advert-->
                <section class="sec-adv">
                    <article><img src="<?php echo $this->getViewFileUrl('images/adv01.png')?>" alt=""></article>
                    <article><img src="<?php echo $this->getViewFileUrl('images/adv02.png')?>" alt=""></article>
                    <article><img src="<?php echo $this->getViewFileUrl('images/adv03.png')?>" alt=""></article>
                </section>
                <!--end adv-->
            </div>
        </div>
    </div>
</div>
