<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
 <button type="submit" style="background-color: #1979c3; width: 156px;"><span style="color: white; font-weight: bold; font-size: 14px;"><?php /* @escapeNotVerified */ echo __('Facebook Sign In') ?></span></button>
 <br>
 <button type="submit" style="background-color: red; width: 156px;"><span style="color: white; font-weight: bold; font-size: 14px;"><?php /* @escapeNotVerified */ echo __('Google Sign In') ?></span></button>